services:
  wordpress:
    image: wordpress:latest
    container_name: wp_dev
    ports:
      - "38280:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp-config/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./wp-config/wp-config.php:/var/www/html/wp-config.php
      - ./wp-config/.htaccess:/var/www/html/.htaccess
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: wp_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
    volumes:
      - ./wp-db:/var/lib/mysql
      - ./wp-config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    restart: unless-stopped
    networks:
      - wordpress_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: wp_cloudflared
    command: tunnel --no-autoupdate run
    volumes:
      - ./cloudflared:/home/nonroot/.cloudflared
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - wordpress_network



networks:
  wordpress_network:
    driver: bridge
